// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Chirp struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
	UserID    uuid.NullUUID
}

type RefreshToken struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	UserID     uuid.NullUUID
	ExpairesAt time.Time
	RevokedAt  sql.NullTime
}

type User struct {
	ID           uuid.UUID
	CretedAt     time.Time
	UpdatedAt    time.Time
	Email        string
	PasswordHash string
}
